#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "Wolfking2015"
git config --global user.email yxdhhaa@126.com
